language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install btrfs-tools libdevmapper-dev libgpgme11-dev libapparmor-dev libseccomp-dev

install:
  - make install.tools

before_script:
  - export PATH=$HOME/gopath/bin:$PATH
  - if test ${TRAVIS_REPO_SLUG} != kubernetes-incubator/cri-o; then
      mkdir -p ${GOPATH}/src/github.com/kubernetes-incubator/cri-o/ ;
      rsync -aHAX ${TRAVIS_BUILD_DIR}/ ${GOPATH}/src/github.com/kubernetes-incubator/cri-o/ ;
      cd ${GOPATH}/src/github.com/kubernetes-incubator/cri-o/ ;
    fi

script:
  - make .gitvalidation
  - make gofmt
  - make lint
  - make integration
  - make docs
  - make

notifications:
  irc: false
